server {
    listen 80;
    server_name uml-assist.danivegam.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name uml-assist.danivegam.com;

    # Rutas donde Docker encontrará los certificados que acabas de generar
    ssl_certificate /etc/letsencrypt/live/uml-assist.danivegam.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/uml-assist.danivegam.com/privkey.pem;

    # A. Tu Frontend (React)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # B. Tus Imágenes (Volumen que ya configuramos)
    location /media/ {
        alias /usr/share/nginx/html/media/;
    }

    # C. Tu Backend (El puente anti-errores)
    location /api/ {
        proxy_pass http://13.59.41.4:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}